// Generated by CoffeeScript 1.3.3

chrome.extension.onConnect.addListener(function(port) {
  return port.onMessage.addListener(function(msg) {
    var response, selector;
    response = (function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = msg.length; _i < _len; _i++) {
        selector = msg[_i];
        _results.push(document.querySelector(selector).innerText);
      }
      return _results;
    })();
    return port.postMessage(response);
  });
});
