// Generated by CoffeeScript 1.3.3
var queryURL,
  __slice = [].slice;

queryURL = function() {
  var callback, selectors, url;
  url = arguments[0], callback = arguments[1], selectors = 3 <= arguments.length ? __slice.call(arguments, 2) : [];
  return chrome.tabs.create({
    active: false
  }, function(tab) {
    return chrome.tabs.executeScript(tab.id, {
      file: "injector.js"
    }, function() {
      var port;
      port = chrome.tabs.connect(tab.id);
      port.postMessage(selectors);
      return port.onMessage.addListener(function(msg) {
        return callback(msg);
      });
    });
  });
};
